[project]
name = "LeL2.0_Server"
version = "0.1.1"
description = "An Inference framework for LeL2.0 with support for Qwen"
requires-python = "==3.11.11"   # évite la résolution pour 3.13/3.14

dependencies = [
  "torch==2.10.0+cu130",
  "transformers==5.6.2",
  "vllm==0.19.1",
  "flash-attn",
  "ray[default]",
  "qwen_vl_utils",
  "torchvision==0.25.0",
  "torchaudio==2.10.0",
  "shapely"
]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }


[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]

[tool.uv.extra-build-variables]
flash-attn = { FLASH_ATTENTION_SKIP_CUDA_BUILD = "FALSE" }

[tool.uv]
override-dependencies = [
  "torch==2.10.0+cu130",
  "transformers==5.6.2",
  "vllm==0.19.1",
  "torchvision==0.25.0+cu130",
  "torchaudio==2.10.0",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true